"""initial tables

Revision ID: 3be74ea281b4
Revises: 
Create Date: 2026-03-15 22:14:39.026673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be74ea281b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fqn', sa.String(length=255), nullable=True),
    sa.Column('connection_name', sa.String(length=100), nullable=True),
    sa.Column('database_name', sa.String(length=100), nullable=True),
    sa.Column('schema_name', sa.String(length=100), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fqn')
    )
    op.create_table('columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upstream_dataset_id', sa.Integer(), nullable=True),
    sa.Column('downstream_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['downstream_dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['upstream_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineage')
    op.drop_table('columns')
    op.drop_table('datasets')
    # ### end Alembic commands ###
